# Generated by Django 4.1.4 on 2023-01-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='PayPal', max_length=100),
        ),
    ]
